---
- name: Install Jenkins
  hosts: localhost
  become: yes
  become_user: root
  
  tasks:
  - name: Update all packages to their latest version
    ansible.builtin.apt:
      name: "*"
      state: latest

  - name: Download key for Jenkins
    ansible.builtin.get_url:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
      dest: /usr/share/keyrings/jenkins-keyring.asc

  - name: repo for Jenkins
    ansible.builtin.apt_repository:
      repo: deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
      state: present
      filename: jenkins.list

  - name: Update all packages to their latest version
    ansible.builtin.apt:
      name: "*"
      state: latest

  - name: Install fontconfig
    shell: apt-get install -y fontconfig    

  - name: Install java
    ansible.builtin.shell: apt install fontconfig openjdk-17-jre -y

  - name: Update the repository cache and update package "nginx" to latest version using default release squeeze-backport
    ansible.builtin.apt:
      name: jenkins
      state: latest

  - name: Start Jenkins service
    service:
      name: jenkins
      state: started
      enabled: yes    